[general]
live_config_reload = true

[window]
dimensions = { columns = 68, lines = 22 }
padding = { x = 3, y = 3 }
opacity = 0.8
decorations = "None"

[font]
size = 8.5
builtin_box_drawing = true

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "l" },
]
